DELETE FROM CACHED_ORDER
WHERE TYPE_ID IN (
	SELECT DISTINCT CACHED_ORDER.TYPE_ID
	FROM CACHED_ORDER
	INNER JOIN STATIC_TYPES
	ON CACHED_ORDER.TYPE_ID = STATIC_TYPES.TYPE_ID
	AND STATIC_TYPES.VOLUME > :volume);