DELETE FROM CACHED_ORDER
WHERE TYPE_ID IN (
	SELECT DISTINCT CACHED_ORDER.TYPE_ID
	FROM CACHED_ORDER
	INNER JOIN STATIC_TYPE
	ON CACHED_ORDER.TYPE_ID = STATIC_TYPE.TYPE_ID
	AND STATIC_TYPE.VOLUME > :volume);