DROP TABLE IF EXISTS TMP_STATIONS;
DROP TABLE IF EXISTS TMP_SELL_ORDERS;
DROP TABLE IF EXISTS TMP_BUY_ORDERS;

CREATE LOCAL TEMPORARY TABLE TMP_STATIONS (
	STATION_ID INTEGER
);

CREATE LOCAL TEMPORARY TABLE TMP_SELL_ORDERS (
	ORDER_PK BIGINT,
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	PRICE DOUBLE,
	VOLUME BIGINT
);

CREATE LOCAL TEMPORARY TABLE TMP_BUY_ORDERS (
	ORDER_PK BIGINT,
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	PRICE DOUBLE,
	VOLUME BIGINT
);