SELECT
TMP_SELL_ORDERS.ORDER_ID,
TMP_SELL_ORDERS.LOCATION_ID,
TMP_SELL_ORDERS.PRICE AS SELL_PRICE,
TMP_BUY_ORDERS.PRICE AS BUY_PRICE,
TMP_SELL_ORDERS.VOLUME AS SELL_VOLUME,
TMP_BUY_ORDERS.VOLUME AS BUY_VOLUME,
(TMP_BUY_ORDERS.VOLUME - TMP_SELL_ORDERS.VOLUME) AS VOLUME,
(TMP_BUY_ORDERS.PRICE - TMP_SELL_ORDERS.PRICE) AS PROFIT
FROM TMP_SELL_ORDERS
INNER JOIN TMP_BUY_ORDERS
ON (TMP_BUY_ORDERS.PRICE - TMP_SELL_ORDERS.PRICE) > (TMP_SELL_ORDERS.PRICE * 0.03);