CREATE CACHED LOCAL TEMPORARY TABLE TMP_STATIONS (
	STATION_ID INTEGER,
	SECURITY_STATUS FLOAT,
);

CREATE CACHED LOCAL TEMPORARY TABLE TMP_AVAL_VOLUMES(
	TYPE_ID INTEGER,
	VOLUME_AVALIABLE BIGINT
);

CREATE UNIQUE INDEX IX_TMP_AVAL_VOLUMES_PK ON TMP_AVAL_VOLUMES (TYPE_ID);

CREATE CACHED LOCAL TEMPORARY TABLE TMP_SELL_ORDERS (
	ORDER_PK BIGINT,
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	LOCATION_SECURITY FLOAT,
	PRICE DOUBLE,
	VOLUME BIGINT,
	MIN_VOLUME BIGINT,
	TYPE_ID INTEGER
);

CREATE INDEX IX_TMP_SELL_ORDERS_TYPE ON TMP_SELL_ORDERS (TYPE_ID);

CREATE CACHED LOCAL TEMPORARY TABLE TMP_BUY_ORDERS (
	ORDER_PK BIGINT,
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	LOCATION_SECURITY FLOAT,
	PRICE DOUBLE,
	VOLUME BIGINT,
	MIN_VOLUME BIGINT,
	TYPE_ID INTEGER
);

CREATE INDEX IX_TMP_BUY_ORDERS_TYPE ON TMP_BUY_ORDERS (TYPE_ID);