CREATE CACHED LOCAL TEMPORARY TABLE TMP_STATIONS (
	STATION_ID INTEGER,
	SECURITY_STATUS DOUBLE,
);

CREATE CACHED LOCAL TEMPORARY TABLE TMP_SELL_ORDERS (
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	SECURITY_STATUS DOUBLE,
	PRICE DOUBLE,
	VOLUME BIGINT,
	MIN_VOLUME BIGINT,
	TYPE_ID INTEGER
);

CREATE INDEX IX_TMP_SELL_ORDERS_TYPE ON TMP_SELL_ORDERS (TYPE_ID);

CREATE CACHED LOCAL TEMPORARY TABLE TMP_BUY_ORDERS (
	ORDER_ID BIGINT,
	LOCATION_ID BIGINT,
	SECURITY_STATUS DOUBLE,
	PRICE DOUBLE,
	VOLUME BIGINT,
	MIN_VOLUME BIGINT,
	TYPE_ID INTEGER
);

CREATE INDEX IX_TMP_BUY_ORDERS_TYPE ON TMP_BUY_ORDERS (TYPE_ID);